### ISSUE TITLE
windows11 22523 mica invalid

### ISSUE THREAD

**Issue by yhsj0919** [alexmercerind/flutter_acrylic#16] opened 2021-12-20 11:46 UTC
windows11 22523 mica invalid

and if enter fullscreen screen will be transparent

![image](https://user-images.githubusercontent.com/7219412/146762471-0a4a0960-8e1b-4d18-a70f-0a28e24df812.png)

![image](https://user-images.githubusercontent.com/7219412/146762547-2f107225-abdc-444e-9903-3b4a3c0ada7e.png)

**Comment by alexmercerind** [comment] 2021-12-21 17:36
Hello @yhsj0919,

I have made d294bc4d54223ed179331ce3fbd7b5b194a0c8da commit to address this issue for newer Windows 11 builds.

I don't have latest Windows 11 build installed, please let me know if the issue is fixed & close this thread.

**Comment by yhsj0919** [comment] 2021-12-22 01:34
mica is ok，but transparent not working when i change it
![GIF 2021-12-22 9-05-08](https://user-images.githubusercontent.com/7219412/147019886-43bdec0e-056b-4601-a0c9-5b42e0f5bf35.gif)

**Comment by alexmercerind** [comment] 2021-12-22 02:21
@yhsj0919
Mica only gives very little transparency because it is meant for persistent long-lived window surfaces.

Acrylic is more transparent.

Tabbed is a new material that came in 22523 which is more transparent compared to Mica. However, undocumented.

**Comment by alexmercerind** [comment] 2021-12-23 14:48
Just updated to 22523, the fix made by me in d294bc4d54223ed179331ce3fbd7b5b194a0c8da is working as intended.

Thanks.

**Closed by alexmercerind** 2021-12-23 14:48 UTC
Labels: bug
